const data = {
    products: [
      {
        _id: '1',
        name: 'HP Elitebook',
        category: 'Laptop',
        image: '/images/p1.jpg',
        price: 35000,
        countInStock: 15,
        brand: 'HP',
        rating: 5,
        numReviews: 10,
        description: 'HP Elitebook 840 G1',
      },
      {
        _id: '2',
        name: 'HP Elitebook',
        category: 'Laptop',
        image: '/images/p1.jpg',
        price: 40000,
        countInStock: 20,
        brand: 'HP',
        rating: 4.5,
        numReviews: 10,
        description: 'HP Elitebook 840 G1 Touch',
      },
      {
        _id: '3',
        name: 'HP Elitebook',
        category: 'Laptop',
        image: '/images/p1.jpg',
        price: 50000,
        countInStock: 10,
        brand: 'HP',
        rating: 4.5,
        numReviews: 10,
        description: 'HP Elitebook 840 G2',
      },
      {
        _id: '4',
        name: 'DELL Vostro',
        category: 'Laptop',
        image: '/images/p2.jpg',
        price: 30000,
        countInStock: 10,
        brand: 'Dell',
        rating: 4,
        numReviews: 10,
        description: 'Dell vostro i5 7th gen',
      },
      {
        _id: '5',
        name: 'Dell Inspiron',
        category: 'Laptop',
        image: '/images/p3.jpg',
        price: 80000,
        countInStock: 10,
        brand: 'Dell',
        rating: 5,
        numReviews: 10,
        description: 'Dell Inspiron v12',
      },
      {
        _id: '6',
        name: 'Dell Inspiron',
        category: 'Laptop',
        image: '/images/p3.jpg',
        price: 90000,
        countInStock: 10,
        brand: 'Dell',
        rating: 5,
        numReviews: 10,
        description: 'Dell Inspiron latest',
      },
      ],
  };
  export default data;
  